/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AsyncBlockIterator {
  next(): Promise<JsElementBlock | null>
}

export declare class OsmReader {
  constructor(path: string)
  streamBlocks(elementFilter?: JsElementFilter | undefined | null, tagFilter?: Array<string> | undefined | null): AsyncBlockIterator
}

export interface JsElementBlock {
  ids: BigInt64Array
  elementType: string
  nodeIds?: [BigInt64Array, Uint32Array]
  latitudes?: Float64Array
  longitudes?: Float64Array
  relationMembers?: [BigInt64Array, Uint8Array, Int32Array, Uint32Array]
  denseTags?: [Uint32Array, Uint32Array, Uint32Array]
  tags?: [Uint32Array, Uint32Array, Uint32Array]
  stringTable: Array<string>
}

export interface JsElementFilter {
  nodes: boolean
  ways: boolean
  relations: boolean
}
